const CONSISTS_OF = "Курс складається з";

export default {
    REGISTRSTION: REGISTRSTION,
    COURSE: COURSE,
    QUOTE_LEFT: QUOTE_LEFT,
    QUOTE_RIGHT: QUOTE_RIGHT,
    SPECIALISTS: SPECIALISTS,
    CONSISTS_OF: CONSISTS_OF,
    COURSES_TITLE: COURSES_TITLE
}